### ISSUE TITLE
Constructor of class Group limits outputs

### ISSUE THREAD

**Issue by GD-L** [andrewvillazon/pbipy#11]
The constructor in `groups.py`  https://github.com/andrewvillazon/pbipy/blob/e8fcdd204d0f30abab254326113f5acd03d41d8f/pbipy/groups.py#L8C1-L12C6  Limits the fields available in admin reporting. 
As a result calling the function `group_data = admin.groups(top = 5000, expand = 'reports,dashboards,datasets,dataflows,workbooks')` limits the output to only `id` and `name`.  That or the `raw` isn't fulling passing through the rest of the raw data.

**Comment by andrewvillazon** [comment]
If the Groups have the values listed in `expand`, and the endpoint supplied them in the response, they _should_ be set on each `Group` object. The `Group.__init__()` only requires an `id` to be supplied, and will set the rest of the attributes using the `_load_from_raw()` method if it received a `raw` argument. There is a [unit test ](https://github.com/andrewvillazon/pbipy/blob/e8fcdd204d0f30abab254326113f5acd03d41d8f/tests/test_admin.py#L621) which confirms this behaviour with the `expand` argument, albeit this only does one element in the `expand`.

If the `Group` objects in your `group_data` have a `name` attribute, that would suggest the endpoint returned it and was correctly set. Are you able to see if the `Group` objects in `group_data` have any of the other data listed in the `expand` argument? Something like this `hasattr(group_data[0], "reports")`, which should return `True` if the Group has a `reports` component **and** it was supplied by the endpoint. You could also inspect the group objects using `dir()`, e.g., `dir(group_data[0])`, to see if the any of the attributes there match what you requested in `expand`.

The other thing to check would be the response from the endpoint. You can do this at the [documentation](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/groups-get-groups-as-admin), using the green "Try It" link on the page, and add the `$expand` value above as a parameter. This should confirm if the endpoint is actually returning what's expected. Alternatively you could re-create a request manually using `requests`, but the documentation link is a bit quicker.

**Comment by GD-L** [comment]
I see. I was not grasping that the lists that were returned were subscriptable. Thanks for tolerating my Qs!

**Comment by andrewvillazon** [comment]
No problem. It's raised a couple of things to test out, so all good.
