### ISSUE TITLE
missing fields

### ISSUE THREAD

**Issue by caroljenner** [andrewvillazon/pbipy#19]
Some of your admin methods are missing attributes, like apps().  Id, name and description is returned but when you look at the documentation  https://learn.microsoft.com/en-us/rest/api/power-bi/admin/apps-get-apps-as-admin#code-try-0

You see workspace id, published by and last update are available. However, their documentation doesn't show it but references it later.  

Groups was another example where what the library is returning is missing attributes listed in the documentation.

**Comment by andrewvillazon** [comment]
I'll take a look. If you're able to, can you use the documentation's "Try it" functionality to make a request using the admin [apps endpoint](https://learn.microsoft.com/en-us/rest/api/power-bi/admin/apps-get-apps-as-admin#code-try-0) you mentioned above? I'd be interested to know what comes back and if that contains the missing attributes.

The way the library is supposed to work, is it will look at the json returned by the api and add any keys it finds as attributes to its objects, such as `App` or `Group`. It seems from what you've mentioned the objects that came back from `apps()` have `id`, `name` and `description`, which suggests api returned them and they were parsed correctly. My guess is the library wasn't able to parse the remaining attributes, _or_ they weren't provided by the api.

**Comment by caroljenner** [comment]
This is what apps returns.  Although the Users never returns for any of mine.  

{
  "@odata.context": "http://wabi-south-central-us-redirect.analysis.windows.net/v1.0/myorg/admin/$metadata#apps",
  "value": [
    {
      "id": "15229df0-c0c0-4393-932f-8ff206f5dfbc",
      "name": "Operations",
      "lastUpdate": "2023-07-12T00:22:39.273Z",
      "description": "Operating Site Details",
      "publishedBy": "Carolyn Oran",
      "workspaceId": "fea56482-cda6-413b-acc0-09497b0f727d",
      "users": []
    },
    {
      "id": "88cc54ef-f59f-4785-9698-d560243ccc2c",
      "name": "Business Development",
      "lastUpdate": "2022-06-02T17:20:25.161Z",
      "description": "Global Pipeline",
      "publishedBy": "Saraa Pengte",
      "workspaceId": "26b65433-1efe-4b21-8544-b46568ba5bb5",
      "users": []
    },
    {
      "id": "8d06702a-f26a-42f8-8282-663a2257d76d",
      "name": "PEGTEST03A",
      "lastUpdate": "2019-01-23T17:39:03.984Z",
      "description": "test",
      "publishedBy": "Parinaz Kallick",
      "workspaceId": "e8ab5ad4-3fdf-4ca3-b138-b97afc1f2631",
      "users": []
    },
    {
      "id": "146e0d74-292d-409b-b907-3928b4815935",
      "name": "Projects",
      "lastUpdate": "2023-09-20T23:32:17.106Z",
      "description": "Project Overview",
      "publishedBy": "Carolyn Oran",
      "workspaceId": "118d4150-a869-48df-a895-1f31b3563a48",
      "users": []
    },
    {
      "id": "5c9e0966-1292-4bf4-9e88-4aa5c8cca0fc",
      "name": "Project Controlling",
      "lastUpdate": "2023-12-08T00:02:04.342Z",
      "description": "Project Controlling App",
      "publishedBy": "Carolyn Oran",
      "workspaceId": "b0fd4607-2eeb-40de-823b-b01feaea5a3a",
      "users": []
    }
  ]
}

**Comment by caroljenner** [comment]
I also mentioned groups, here's what that returns:

{
  "@odata.context": "http://wabi-south-central-us-redirect.analysis.windows.net/v1.0/myorg/admin/$metadata#groups",
  "@odata.count": 1691,
  "value": [
    {
      "id": "d187e338-c90d-4724-a12b-6a2514cadba7",
      "isReadOnly": false,
      "isOnDedicatedCapacity": false,
      "capacityMigrationStatus": "",
      "description": "Dynamics 365 Reporting",
      "type": "Workspace",
      "state": "Active",
      "hasWorkspaceLevelSettings ": false,
      "name": "D365 Reporting"
    },
    {
      "id": "26b65433-1efe-4b21-8544-b46568ba5bb5",
      "isReadOnly": false,
      "isOnDedicatedCapacity": true,
      "capacityId": "879A6594-2392-4B6E-BD3E-83B4B427BA17",
      "capacityMigrationStatus": "Migrated",
      "defaultDatasetStorageFormat": "Small",
      "type": "Workspace",
      "state": "Active",
      "hasWorkspaceLevelSettings ": false,
      "name": "Business Development"
    },
    {
      "id": "fea56482-cda6-413b-acc0-09497b0f727d",
      "isReadOnly": false,
      "isOnDedicatedCapacity": true,
      "capacityId": "879A6594-2392-4B6E-BD3E-83B4B427BA17",
      "capacityMigrationStatus": "Migrated",
      "defaultDatasetStorageFormat": "Small",
      "type": "Workspace",
      "state": "Active",
      "hasWorkspaceLevelSettings ": false,
      "name": "Operations"
    },
    {
      "id": "4c4b19b6-a895-467a-b286-cb4603c4f4f4",
      "isReadOnly": false,
      "isOnDedicatedCapacity": false,
      "capacityMigrationStatus": "",
      "description": "Data based off PegDev18A environment",
      "type": "Workspace",
      "state": "Active",
      "hasWorkspaceLevelSettings ": false,
      "name": "PEGDEV18A"
    },
    {
      "id": "b46ecffa-b2d0-4c46-ada8-753a4d96ff82",
      "isReadOnly": false,
      "isOnDedicatedCapacity": false,
      "capacityMigrationStatus": "",
      "description": "pegtest01362a573c9869321ddevaos.cloudax.dynamics.com",
      "type": "Workspace",
      "state": "Active",
      "hasWorkspaceLevelSettings ": false,
      "name": "PEGTEST01DEV"
    }
  ]
}

**Comment by andrewvillazon** [comment]
Thanks for that. When I test with your data I'm able to see `Group` and `App` objects with all the fields that are returned by your api, for both apps and groups. This would indicate the library is handling the data as expected. Are you able to test for the existence of the attributes on the objects that are returned by `admin.apps()` and `admin.groups()`? 

Something like this should do it, and return `True` for all of the `print()` lines. Let me know if that works.

```python
apps = admin.apps()

print(hasattr(apps[0], "workspace_id"))
print(hasattr(apps[0], "published_by"))
print(hasattr(apps[0], "last_update"))
```

A couple of other things. The library converts the JSON key names to snake case to be consistent with Python. If you're looking for `workspaceId`, this would be turned into `workspace_id`.

The API only includes data for a given object if that data is available. If the data isn't set, access restricted, etc., then the api wont return it. Because of this you'll get some library objects with an attribute and some without. So in your groups data above, only some of the `Group` objects will have a `default_dataset_storage_format` attribute.

To get the extra information that's shown in the examples in the groups documentation, you'd need to include the `expand` argument, which takes a list of types e.g., `users`, `reports`, `dashboards`. This tells the api you want more information included on the object.

```
groups_extra = admin.groups(expand="reports, datasets")
```

Hope that makes sense.

**Comment by caroljenner** [comment]
Thank you for your response, it helps a lot!!
