### ISSUE TITLE
request methods for /admin/workspaces

### ISSUE THREAD

**Issue by copdips** [andrewvillazon/pbipy#27]
Hello,

Thanks a lot for this great job to provide the Python wrapper for PowerBI.
The REST API constains also some `/admin/workspaces` endpoints, would you plan to implement them ?

For example, https://learn.microsoft.com/en-us/rest/api/power-bi/admin/workspace-info-get-scan-result

**Comment by andrewvillazon** [comment]
This should be do-able. I'll have a think about how the api should look for these and put something together in the next week or so.

**Comment by andrewvillazon** [comment]
@copdips - I've put some additional methods together that wrap the scanner APIs:

* `Admin.workspaces`
* `Admin.initiate_scan`
* `Admin.scan_status`
* `Admin.scan_result`

Unfortunately I don't have access to an endpoint to test, but feel free to test it out and let me know if it works. You should be able to install and try using below. If there's no errors I'll merge and release.

```
pip install git+https://github.com/andrewvillazon/pbipy@enhancement/27/request-methods-for-admin-workspaces
```

**Comment by copdips** [comment]
Thx for this PR, it's all good after the test.
