### ISSUE TITLE
get dataflows JSON

### ISSUE THREAD

**Issue by fafernandezc** [andrewvillazon/pbipy#3]
Would be really helpful to use this library to extract the dataflow definition into a JSON file

[Dataflows - Get Dataflow](https://learn.microsoft.com/en-us/rest/api/power-bi/dataflows/get-dataflow)

**Comment by andrewvillazon** [comment]
The `Dataflow` object has a `raw` attribute which should give you the json as it was received from the endpoint (and handled by `requests`) You could write this json to file. Something like:

```python
import json
from pbipy import PowerBI

pbi = PowerBI(bearer_token)
my_dataflow = pbi.dataflow("your dataflow id", group="workspace id if applicable")
dataflow_def = my_dataflow.raw

with open("export file path", "w") as out_file:
    json.dump(dataflow_def, outfile)
```

This endpoint is unique compared to others in that it returns a json file, as opposed to a json response. To keep things consistent with the rest of the library, the `pbi.dataflow()` method takes this file and turns it into a `Dataflow` object. However you can access the json via the `raw` property. This is also the same for the rest of the objects in the library.

Does that help?
