### ISSUE TITLE
Feature Request: Get Embed Token for Reports

### ISSUE THREAD

**Issue by JVickery-TBS** [andrewvillazon/pbipy#31]
It would be useful if the `Report` class could support the `https://api.powerbi.com/v1.0/myorg/groups/{GROUP ID}/reports/{REPORT ID}/GenerateToken` API endpoint. So that we could generate an embed token for a given Report.

**Comment by andrewvillazon** [comment]
I think this should be do-able. I note that Microsoft recommends use of the [Generate Token Endpoint](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token) rather than the more specific Report Endpoint. Will have a think what this should look like and where it should sit.

**Comment by JVickery-TBS** [comment]
@andrewvillazon cool. Yeah I personally had to use the specific one just how we embed reports in our framework. We would not know the IDs of multiple reports/datasets at that point in the framework we use.

Could be good to support bother here I guess? The more specific one in the `Report` class, and then the better one in a higher class?
