### ISSUE TITLE
Get report visuals data results

### ISSUE THREAD

**Issue by CrasCris** [andrewvillazon/pbipy#38]
If there posible to get the data of visual objets of a report ?, i alreay creade de pbi.report() and is fine, but i need to create a script that get data for a visual object of that specific report

**Comment by andrewvillazon** [comment]
Unfortunately I don't think this data is available through the Rest API. If you knew the specifics of the visual, you could try using `Dataset.execute_queries` which lets you execute a DAX query against a Dataset. You could then run a DAX query that tries to replicate the data in the visual.

**Comment by CrasCris** [comment]
> Unfortunately I don't think this data is available through the Rest API. If you knew the specifics of the visual, you could try using `Dataset.execute_queries` which lets you execute a DAX query against a Dataset. You could then run a DAX query that tries to replicate the data in the visual.

Thanks

**Comment by WarrenGraham** [comment]
@CrasCris I've experienced this error, solution is to use DAX query under visual as @andrewvillazon said above. If you don't have knowledge about DAX u can use autogenerated by PowerBI Desktop engine. You can find it in Performance analyzer pane. I used build in sample as example.

![image](https://github.com/andrewvillazon/pbipy/assets/62251606/77ae2826-5ae0-4587-86e7-d3841e13db34)
