### ISSUE TITLE
Unable to access pbi datasets and groups

### ISSUE THREAD

**Issue by arnabdasgupta04** [andrewvillazon/pbipy#6]
I got the respective bearer token to connect to pbi app services using pbipy, but still, I am getting the below error while doing the same. Please guide urgently. Please find the below snippets for reference.

**Comment by andrewvillazon** [comment]
@arnabdasgupta04 - I've deleted the image you posted, just because it contains your bearer token which is authentication information. Are you able to paste, as text, the full error message, and without the token? I can see only part of the error, and would need to see the full message to understand what's happening.

**Comment by arnabdasgupta04** [comment]
@andrewvillazon Please find the below error I got.


JSONDecodeError: Expecting value: line 1 column 1 (char 0)
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File /databricks/python/lib/python3.10/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File /usr/lib/python3.10/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File /usr/lib/python3.10/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335 
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File /usr/lib/python3.10/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
File <command-2004076745113406>, line 27
     22 pbi = PowerBI(access_token)
     24 '''groups = pbi.groups()
     25 for group in groups:
     26     print(group.name,group.id)'''
---> 27 sales = pbi.dataset("9bd667ee-89af-4c08-ad0b-10329b633820")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/pbipy/powerbi.py:401, in PowerBI.dataset(self, dataset, group)
    398     return dataset
    400 dataset = Dataset(dataset, self.session, group_id=group)
--> 401 dataset.load()
    403 return dataset

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/pbipy/resources.py:54, in Resource.load(self)
     53 def load(self):
---> 54     raw = self.get_raw(self.base_path, self.session)
     55     self._load_from_raw(raw)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/pbipy/utils.py:463, in RequestsMixin.get_raw(self, resource, session, params, **kwargs)
    460     return self.parse_raw(raw)
    462 except Exception as e:
--> 463     raise e

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/pbipy/utils.py:457, in RequestsMixin.get_raw(self, resource, session, params, **kwargs)
    433 """
    434 Request an api resource, parse the response json, and return the
    435 parsed json.
   (...)
    453     Error encountered during the request process.
    454 """
    456 try:
--> 457     response = self.get(resource, session, params, **kwargs)
    458     raw = response.json()
    460     return self.parse_raw(raw)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/pbipy/utils.py:421, in RequestsMixin.get(self, resource, session, params, success_codes)
    415 response = session.get(resource, params=params)
    417 if response.status_code not in success_codes:
    418     raise HTTPError(
    419         f"""Encountered api error. Response: 
    420         
--> 421         {json.dumps(response.json(), indent=True)})"""
    422     )
    424 return response

File /databricks/python/lib/python3.10/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by andrewvillazon** [comment]
My guess is your Powerbi instance is returning a non-200 response code to the request for the dataset, possibly a 400 range response, and this response does not include a json component. I would check that the api is setup on your Power BI instance, correctly configured, or permits you to access it.

The error handling in `pbipy` is assuming that the response from the api will supply a json component, which I can see isn't guaranteed. I'll update the error handling to reflect this.

**Comment by andrewvillazon** [comment]
Closing and moving to #7
